chg: dev: Added Diagnostics partition
Change-Id: If7735b18b8db322436be96a6402b0bb9bec1f4a4
Signed-off-by: srinsriv <srinivasan.srivatsan@hpe.com>

diff --git a/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in b/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
--- a/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
+++ b/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
@@ -29,10 +29,12 @@ echo -e "${bold}OpenSwitch ONIE installer (version $installer_version) for $MACH
 attr_bitmask="0x0000000000000001"
 label="OpenSwitch"
 config_label="$label Conf"
+diags_label="$label Diags"
 primary_label="$label 1"
 secondary_label="$label 2"
 mount_point=/mnt/ops
 config_mount_point=/mnt/ops/tmp
+diags_mount_point=/diags
 INSTALLING_FROM_OPS=false
 
 # Install NOS on the same block device as ONIE
@@ -67,6 +69,7 @@ setup_nos_partitions()
 
     # Find if we have a config partition
     CONFIG_PARTITION_NUMBER=$(get_partition_number "$config_label")
+    DIAGS_PARTITION_NUMBER=$(get_partition_number "$diags_label")
     PRIMARY_PARTITION_NUMBER=$(get_partition_number "$primary_label")
     SECONDARY_PARTITION_NUMBER=$(get_partition_number "$secondary_label")
     if ! $OPS_CLEAN_INSTALL && [ -n "$CONFIG_PARTITION_NUMBER" ]; then
@@ -76,10 +79,14 @@ setup_nos_partitions()
         # We have a config partition, find the active partition
         if ! $INSTALLING_FROM_OPS ; then
             mount -t ext4 ${NOS_DISK}${CONFIG_PARTITION_NUMBER} $config_mount_point
+            echo -e "${bold} --- Mount diags partition (${NOS_DISK}${DIAGS_PARTITION_NUMBER}) --- ${low}"
+            mkdir -p $diags_mount_point
+            mount -t ext4 ${NOS_DISK}${DIAGS_PARTITION_NUMBER} $diags_mount_point
         fi
         active_grub_entry=$(grub-editenv $config_mount_point/boot/grub/grubenv list | awk -F= '/^saved_entry/ { print $2 }')
         if ! $INSTALLING_FROM_OPS ; then
             umount $config_mount_point
+            umount $diags_mount_point
         fi
 
         if [ -n "$active_grub_entry" ] && [ $active_grub_entry == 0 ]; then
@@ -137,8 +144,23 @@ setup_nos_partitions()
             partprobe ${NOS_DISK}
         fi
 
+        if [ -z "$DIAGS_PARTITION_NUMBER" ] ; then
+            DIAGS_PARTITION_NUMBER=$((${CONFIG_PARTITION_NUMBER} + 1))
+            echo
+            echo -e "${bold} --- Creating the diags partition (#${DIAGS_PARTITION_NUMBER}, label $diags_label) --- ${low}"
+            first_sector=$(($(sgdisk -i $((${DIAGS_PARTITION_NUMBER} - 1)) ${NOS_DISK} | grep 'Last sector:' | awk '{ print $3 }') + 1))
+            sgdisk --new=${DIAGS_PARTITION_NUMBER}:${first_sector}:+${DIAGS_PARTITION_SIZE} \
+               --typecode=${DIAGS_PARTITION_NUMBER}:8300 \
+               --attributes=${DIAGS_PARTITION_NUMBER}:=:$attr_bitmask \
+               --change-name=${DIAGS_PARTITION_NUMBER}:"$diags_label"  ${NOS_DISK} || {
+                    echo -e "${red}ERROR${normal}: Failed to create partition ${NOS_DISK}${DIAGS_PARTITION_NUMBER}!"
+                    exit 1
+                }
+            partprobe ${NOS_DISK}
+        fi
+
         if [ -z "$PRIMARY_PARTITION_NUMBER" ] ; then
-            PRIMARY_PARTITION_NUMBER=$((${CONFIG_PARTITION_NUMBER} + 1))
+            PRIMARY_PARTITION_NUMBER=$((${DIAGS_PARTITION_NUMBER} + 1))
             echo
             echo -e "${bold} --- Creating the primary partition (#${PRIMARY_PARTITION_NUMBER}, label $primary_label) --- ${low}"
             first_sector=$(($(sgdisk -i $((${PRIMARY_PARTITION_NUMBER} - 1)) ${NOS_DISK} | grep 'Last sector:' | awk '{ print $3 }') + 1))
@@ -172,6 +194,9 @@ setup_nos_partitions()
         echo -e "${bold} --- Formatting configuration partition in ext4 --- ${low}"
         mkfs.ext4 -L "$config_label" -q ${NOS_DISK}${CONFIG_PARTITION_NUMBER}
         echo
+        echo -e "${bold} --- Formatting diagnostics partition in ext4 --- ${low}"
+        mkfs.ext4 -L "$diags_label" -q ${NOS_DISK}${DIAGS_PARTITION_NUMBER}
+        echo
         echo -e "${bold} --- Formatting primary partition in ext4 --- ${low}"
         mkfs.ext4 -L "$primary_label" -q ${NOS_DISK}${PRIMARY_PARTITION_NUMBER}
         echo
@@ -200,6 +225,7 @@ populate_rootfs()
     echo -e "${bold} --- Installing $label GRUB --- ${low}"
     sed -i -e "s/OPENSWITCH_PRIMARY_PART_NUM/${PRIMARY_PARTITION_NUMBER}/g" \
            -e "s/OPENSWITCH_SECONDARY_PART_NUM/${SECONDARY_PARTITION_NUMBER}/g" \
+           -e "s/OPENSWITCH_DIAGS_PART_NUM/${DIAGS_PARTITION_NUMBER}/g" \
            -e "s/OPENSWITCH_CONFIG_PART_NUM/${CONFIG_PARTITION_NUMBER}/g" \
            -e "s/OPENSWITCH_CONFIG_CONSOLE/${CONFIG_CONSOLE}/g" \
        ${mount_point}/boot/grub/grub.cfg
@@ -212,6 +238,8 @@ populate_rootfs()
     # Update the grub environment
     if ! $INSTALLING_FROM_OPS ; then
         mount -t ext4 ${NOS_DISK}${CONFIG_PARTITION_NUMBER} $config_mount_point
+        mount -t ext4 ${NOS_DISK}${DIAGS_PARTITION_NUMBER} $diags_mount_point
+        echo -e "${bold} --- Mounting diags partition (${NOS_DISK}${DIAGS_PARTITION_NUMBER}) --- ${low}"
         mkdir -p ${config_mount_point}/boot/grub/
         # We are mounting the config inside the installing partition to allow the chroot to reach it
         chroot ${mount_point} /usr/bin/grub-editenv /tmp/boot/grub/grubenv set saved_entry=${INSTALLING_BOOT_ENTRY}
@@ -264,6 +292,7 @@ else
 
     INSTALLING_FROM_OPS=true
     config_mount_point=/var/local
+    diags_mount_point=/diags
 fi
 
 banner() {
@@ -297,6 +326,8 @@ mkdir -p $mount_point
 if ! $INSTALLING_FROM_OPS ; then
     umount $config_mount_point 2>/dev/null
     mkdir -p $config_mount_point
+    umount $diags_mount_point 2>/dev/null
+    mkdir -p $diags_mount_point
 fi
 setup_nos_partitions
 populate_rootfs
