Support for advanced partition scheme
Change-Id: Ie114854f335fc25c95d07440abd263f209787063
Signed-off-by: Diego Dompe <dompe@hp.com>

diff --git a/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in b/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
--- a/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
+++ b/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
@@ -12,7 +12,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-installer_version="0.5"
+installer_version="1.0"
 
 # check if stdout is a terminal...
 if [ -t 1 ]; then
@@ -28,53 +28,166 @@ echo -e "${bold}OpenSwitch ONIE installer (version $installer_version) for $MACH
 # Set system partition (bit 0) attributes.
 attr_bitmask="0x0000000000000001"
 label="OpenSwitch"
-mount_point=/mnt/nos
+config_label="$label Conf"
+primary_label="$label 1"
+secondary_label="$label 2"
+mount_point=/mnt/ops
+config_mount_point=/mnt/ops/tmp
 
-setup_nos_partition()
+# Install NOS on the same block device as ONIE
+NOS_DISK=$(blkid | awk '/LABEL="ONIE-BOOT"/ {print substr ($1,0,8)}')
+ACTIVE_PARTITION_NUMBER=-1
+INACTIVE_PARTITION_NUMBER=-1
+INSTALLING_PARTITION_NUMBER=-1
+INSTALLING_PARTITION_LABEL=""
+INSTALLING_BOOT_ENTRY=0
+
+setup_nos_partitions()
 {
-    echo
-    echo -e "${bold} --- Creating a new NOS partition (#${NOS_PARTITION_NUMBER}, label $label) --- ${low}"
-    first_sector=$(($(sgdisk -i $((${NOS_PARTITION_NUMBER} - 1)) ${NOS_DISK} | grep 'Last sector:' | awk '{ print $3 }') + 1))
-    sgdisk --new=${NOS_PARTITION_NUMBER}:${first_sector}:+${NOS_PARTITION_SIZE} \
-       --typecode=${NOS_PARTITION_NUMBER}:8300 \
-       --attributes=${NOS_PARTITION_NUMBER}:=:$attr_bitmask \
-       --change-name=${NOS_PARTITION_NUMBER}:"$label"  ${NOS_DISK} || {
-            echo -e "${red}ERROR${normal}: Failed to create partition ${NOS_DISK}${NOS_PARTITION_NUMBER}!"
+    # Find old legacy partitions and remove them
+    # This can be removed in the future
+    OLD_PARTITION_NUMBER=$(blkid | awk "/LABEL=\"$label\"/ {print substr (\$1,9,length(\$1)-9)}")
+    if [ -n "$OLD_PARTITION_NUMBER" ]; then
+        echo
+        echo -e "${bold} --- Removing legacy $label partition --- ${low}"
+        sgdisk -d ${OLD_PARTITION_NUMBER} ${NOS_DISK} || {
+            echo -e "${red}ERROR${normal}: Failed to delete partition ${NOS_DISK}${OLD_PARTITION_NUMBER}!"
             exit 1
         }
-    partprobe ${NOS_DISK}
+        partprobe ${NOS_DISK}
+    fi
 
-    echo
-    echo -e "${bold} --- Formatting NOS partition in ext4 --- ${low}"
-    mkfs.ext4 -L "$label" -q ${NOS_DISK}${NOS_PARTITION_NUMBER}
+    # Find if we have a config partition
+    CONFIG_PARTITION_NUMBER=$(blkid | awk "/LABEL=\"$config_label\"/ {print substr (\$1,9,length(\$1)-9)}")
+    PRIMARY_PARTITION_NUMBER=$(blkid | awk "/LABEL=\"$primary_label\"/ {print substr (\$1,9,length(\$1)-9)}")
+    SECONDARY_PARTITION_NUMBER=$(blkid | awk "/LABEL=\"$secondary_label\"/ {print substr (\$1,9,length(\$1)-9)}")
+    if [ -n "$CONFIG_PARTITION_NUMBER" ]; then
+        echo
+        echo -e "${bold} --- Existing installation found, installing on the inactive partition --- ${low}"
+
+        # We have a config partition, find the active partition
+        mount -t ext4 ${NOS_DISK}${CONFIG_PARTITION_NUMBER} $config_mount_point
+        active_grub_entry=$(grub-editenv $config_mount_point/boot/grub/grubenv list | awk -F= '/^saved_entry/ { print $2 }')
+        umount $config_mount_point
+
+        if [ -n "$active_grub_entry" ] && [ $active_grub_entry == 0 ]; then
+            INACTIVE_PARTITION_LABEL="$secondary_label"
+            INACTIVE_PARTITION_NUMBER=$SECONDARY_PARTITION_NUMBER
+            INSTALLING_BOOT_ENTRY=1
+        else
+            INACTIVE_PARTITION_LABEL="$primary_label"
+            INACTIVE_PARTITION_NUMBER=$PRIMARY_PARTITION_NUMBER
+            INSTALLING_BOOT_ENTRY=0
+        fi
+
+        echo
+        echo -e "${bold} --- Formating the inactive partition ($INACTIVE_PARTITION_LABEL, #${INACTIVE_PARTITION_NUMBER}) --- ${low}"
+        mkfs.ext4 -L "$INACTIVE_PARTITION_LABEL" -q ${NOS_DISK}${INACTIVE_PARTITION_NUMBER} || {
+            echo -e "${red}ERROR${normal}: Failed to format partition ${NOS_DISK}${INACTIVE_PARTITION_NUMBER}!"
+            exit 1
+        }
+        INSTALLING_PARTITION_NUMBER=${INACTIVE_PARTITION_NUMBER}
+        INSTALLING_PARTITION_LABEL=${INACTIVE_PARTITION_LABEL}
+    else
+        echo
+        echo -e "${bold} --- Not previous installation found, performing a clean installation --- ${low}"
+
+        # Find next available partitions
+        CONFIG_PARTITION_NUMBER=$(($(sgdisk -p ${NOS_DISK} | awk END'{print $1}') + 1))
+        PRIMARY_PARTITION_NUMBER=$((${CONFIG_PARTITION_NUMBER} + 1))
+        SECONDARY_PARTITION_NUMBER=$((${PRIMARY_PARTITION_NUMBER} + 1))
+
+        if [ -z "${CONFIG_PARTITION_NUMBER}" ]; then
+            echo -e "${red}ERROR${normal}: Failed to find an available partitions for installation!"
+            exit 1
+        fi
+
+        # Create the partitions
+        echo
+        echo -e "${bold} --- Creating the configuration partition (#${CONFIG_PARTITION_NUMBER}, label $config_label) --- ${low}"
+        first_sector=$(($(sgdisk -i $((${CONFIG_PARTITION_NUMBER} - 1)) ${NOS_DISK} | grep 'Last sector:' | awk '{ print $3 }') + 1))
+        sgdisk --new=${CONFIG_PARTITION_NUMBER}:${first_sector}:+${CONFIG_PARTITION_SIZE} \
+           --typecode=${CONFIG_PARTITION_NUMBER}:8300 \
+           --attributes=${CONFIG_PARTITION_NUMBER}:=:$attr_bitmask \
+           --change-name=${CONFIG_PARTITION_NUMBER}:"$config_label"  ${NOS_DISK} || {
+                echo -e "${red}ERROR${normal}: Failed to create partition ${NOS_DISK}${CONFIG_PARTITION_NUMBER}!"
+                exit 1
+            }
+        partprobe ${NOS_DISK}
+        echo
+        echo -e "${bold} --- Creating the primary partition (#${PRIMARY_PARTITION_NUMBER}, label $primary_label) --- ${low}"
+        first_sector=$(($(sgdisk -i $((${PRIMARY_PARTITION_NUMBER} - 1)) ${NOS_DISK} | grep 'Last sector:' | awk '{ print $3 }') + 1))
+        sgdisk --new=${PRIMARY_PARTITION_NUMBER}:${first_sector}:+${NOS_PARTITION_SIZE} \
+           --typecode=${PRIMARY_PARTITION_NUMBER}:8300 \
+           --attributes=${PRIMARY_PARTITION_NUMBER}:=:$attr_bitmask \
+           --change-name=${PRIMARY_PARTITION_NUMBER}:"$primary_label"  ${NOS_DISK} || {
+                echo -e "${red}ERROR${normal}: Failed to create partition ${NOS_DISK}${PRIMARY_PARTITION_NUMBER}!"
+                exit 1
+            }
+        partprobe ${NOS_DISK}
+        echo
+        echo -e "${bold} --- Creating the secondary partition (#${SECONDARY_PARTITION_NUMBER}, label $secondary_label) --- ${low}"
+        first_sector=$(($(sgdisk -i $((${SECONDARY_PARTITION_NUMBER} - 1)) ${NOS_DISK} | grep 'Last sector:' | awk '{ print $3 }') + 1))
+        sgdisk --new=${SECONDARY_PARTITION_NUMBER}:${first_sector}:+${NOS_PARTITION_SIZE} \
+           --typecode=${SECONDARY_PARTITION_NUMBER}:8300 \
+           --attributes=${SECONDARY_PARTITION_NUMBER}:=:$attr_bitmask \
+           --change-name=${SECONDARY_PARTITION_NUMBER}:"$secondary_label"  ${NOS_DISK} || {
+                echo -e "${red}ERROR${normal}: Failed to create partition ${NOS_DISK}${SECONDARY_PARTITION_NUMBER}!"
+                exit 1
+            }
+        partprobe ${NOS_DISK}
+
+        # Format the partitions
+        echo
+        echo -e "${bold} --- Formatting configuration partition in ext4 --- ${low}"
+        mkfs.ext4 -L "$config_label" -q ${NOS_DISK}${CONFIG_PARTITION_NUMBER}
+        echo
+        echo -e "${bold} --- Formatting primary partition in ext4 --- ${low}"
+        mkfs.ext4 -L "$primary_label" -q ${NOS_DISK}${PRIMARY_PARTITION_NUMBER}
+        echo
+        echo -e "${bold} --- Formatting secondary partition in ext4 --- ${low}"
+        mkfs.ext4 -L "$secondary_label" -q ${NOS_DISK}${SECONDARY_PARTITION_NUMBER}
+
+        INSTALLING_PARTITION_NUMBER=${PRIMARY_PARTITION_NUMBER}
+        INSTALLING_PARTITION_LABEL=$primary_label
+        INSTALLING_BOOT_ENTRY=0
+    fi
 }
 
 populate_rootfs()
 {
     echo
-    echo -e "${bold} --- Populating the root filesystem --- ${low}"
-    mkdir -p $mount_point
-    mount -t ext4 ${NOS_DISK}${NOS_PARTITION_NUMBER} $mount_point
+    echo -e "${bold} --- Populating the root filesystem at partition ${INSTALLING_PARTITION_LABEL} (${NOS_DISK}${INSTALLING_PARTITION_NUMBER}) --- ${low}"
+    mount -t ext4 ${NOS_DISK}${INSTALLING_PARTITION_NUMBER} $mount_point
     prev_dir=$(pwd)
     source_path=$(realpath "$0")
     cd $mount_point
     sed -e '1,/^exit_marker$/d' "$source_path" | gzip -cd - | cpio -idm || {
-        echo -e "${red}ERROR${normal}: Failed to populate the root filesystem on ${NOS_DISK}${NOS_PARTITION_NUMBER}!"
+        echo -e "${red}ERROR${normal}: Failed to populate the root filesystem on ${NOS_DISK}${INSTALLING_PARTITION_NUMBER}!"
         exit 1
     }
     echo
-    echo -e "${bold} --- Installing NOS GRUB --- ${low}"
-    sed -i -e "s/OPENSWITCH_BOOT_PART_NUM/${NOS_PARTITION_NUMBER}/g" ${mount_point}/boot/grub/grub.cfg
+    echo -e "${bold} --- Installing $label GRUB --- ${low}"
+    sed -i -e "s/OPENSWITCH_PRIMARY_PART_NUM/${PRIMARY_PARTITION_NUMBER}/g" \
+           -e "s/OPENSWITCH_SECONDARY_PART_NUM/${SECONDARY_PARTITION_NUMBER}/g" \
+           -e "s/OPENSWITCH_CONFIG_PART_NUM/${CONFIG_PARTITION_NUMBER}/g" \
+       ${mount_point}/boot/grub/grub.cfg
     ${mount_point}/usr/sbin/grub-install --force --boot-directory ${mount_point}/boot --recheck ${NOS_DISK} || {
-        echo -e "${red}ERROR${normal}: Failed to install the NOS GRUB!"
+        echo -e "${red}ERROR${normal}: Failed to install the $label GRUB!"
         exit 1
     }
     chattr +i ${mount_point}/boot/grub/i386-pc/core.img
 
+    # Update the grub environment
+    mount -t ext4 ${NOS_DISK}${CONFIG_PARTITION_NUMBER} $config_mount_point
+    mkdir -p ${config_mount_point}/boot/grub/
+    # We are mounting the config inside the installing partition to allow the chroot to reach it
+    chroot ${mount_point} /usr/bin/grub-editenv /tmp/boot/grub/grubenv set saved_entry=${INSTALLING_BOOT_ENTRY}
+    umount $config_mount_point
+
     cd $prev_dir
     umount $mount_point
 }
-
 
 # Make sure we are running in the ONIE environment.
 [ "$(uname -n)" != "onie" ] && {
@@ -91,32 +204,12 @@ populate_rootfs()
     exit 1
 }
 
-NOS_DISK=$(blkid | awk "/LABEL=\"$label\"/ {print substr (\$1,0,8)}")
-if [ -n "${NOS_DISK}" ]; then
-    NOS_PARTITION_NUMBER=$(blkid | awk "/LABEL=\"$label\"/ {print substr (\$1,9,length(\$1)-9)}")
-
-    echo
-    echo -e "${bold} ---  Removing existing NOS partition (#${NOS_PARTITION_NUMBER}) --- ${low}"
-    # Delete the partition
-    sgdisk -d ${NOS_PARTITION_NUMBER} ${NOS_DISK} || {
-        echo -e "${red}ERROR${normal}: Failed to delete partition ${NOS_DISK}${NOS_PARTITION_NUMBER}!"
-        exit 1
-    }
-    partprobe ${NOS_DISK}
-else
-    # Install NOS on the same block device as ONIE
-    NOS_DISK=$(blkid | awk '/LABEL="ONIE-BOOT"/ {print substr ($1,0,8)}')
-
-    # Find next available partition
-    NOS_PARTITION_NUMBER=$(($(sgdisk -p ${NOS_DISK} | awk END'{print $1}') + 1))
-
-    if [ -z "${NOS_PARTITION_NUMBER}" ]; then
-        echo -e "${red}ERROR${normal}: Failed to find an available partition for installation!"
-        exit 1
-    fi
-fi
-
-setup_nos_partition
+# Clear any left-over mounts
+umount $mount_point 2>/dev/null
+umount $config_mount_point 2>/dev/null
+mkdir -p $mount_point
+mkdir -p $config_mount_point
+setup_nos_partitions
 populate_rootfs
 
 echo
